version: '3.0' # Don't change this
services:
    kedro:
        image: kedro_airflow
        tty: true
        volumes:
            - ./airflow_test:/usr/local/airflow/airflow_test
        command: bash -c "cd airflow_test && kedro build-reqs && kedro install && kedro run && kedro airflow create && kedro airflow deploy"